apiVersion: v1
kind: ConfigMap
metadata:
   name: #{k8.CONFIG_MAP_NAME}# 
   namespace: #{k8.APP_NAMESPACE}#
data:
   appsettings.json: |-
     {
        "AppId": "#{app.AppId}#",
        "AppSecret": "#{app.AppSecret}#",
        "MongoDBConnection": "#{app.MongoDBConnection}#",
        "Database": "#{app.Database}#",
        "StorageConnection": "#{app.StorageConnection}#",
        "StorageContainerName": "#{app.StorageContainerName}#",
        "RedisCacheConnectionString": "#{app.RedisCacheConnectionString}#",
        "BuildVersion": "#{app.BuildVersion}#",
        "Serilog": {
            "WriteTo": [
              { 
                "Name": "#{app.Serilog.WriteTo.Name}#" 
              },
              {
                "Name": "#{app.Serilog.WriteTo.Name.Http}#",
                "Args": {
                    "requestUri": "#{app.Serilog.WriteTo.Args.requestUri}#"
                }
              },
              {
                "Name": "#{app.Serilog.WriteTo.Name.Elasticsearch}#",
                "Args": {
                  "NodeUris": "#{app.Serilog.WriteTo.Args.NodeUris}#",
                  "IndexFormat": "#{app.Serilog.WriteTo.Args.IndexFormat}#"
                }
              }
            ],
            "MinimumLevel": {
              "Default": "#{app.Serilog.MinimumLevel.Default}#",
              "Override": {
                "Microsoft": "#{app.Serilog.MinimumLevel.Override.Microsoft}#",
                "System": "#{app.Serilog.MinimumLevel.Override.System}#"
              }
            }
        },
        "MongoConfigurationProvider": {
            "CollectionName": "#{app.MongoConfigurationProvider.CollectionName}#" ,
            "DatabaseName": "#{app.MongoConfigurationProvider.DatabaseName}#" ,
            "ReloadOnChange": "#{app.MongoConfigurationProvider.ReloadOnChange}#" 
        },  
        "AzureKeyVaultConfig": {
            "TenantId": "#{app.AzureKeyVaultConfig.TenantId}#" ,
            "KeyVault": "#{app.AzureKeyVaultConfig.KeyVault}#" ,
            "AppId": "#{app.AppId}#" ,
            "AppSecret": "#{app.AppSecret}#"
        }         
     }